CREATE SCHEMA data_warehouse_metro ;

CREATE TABLE data_warehouse_metro.Customer (
	CUSTOMER_ID VARCHAR(4) NOT NULL, 
	CUSTOMER_NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Customer_PK PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE data_warehouse_metro.Store (
	STORE_ID VARCHAR(4) NOT NULL,
	STORE_NAME VARCHAR(20) NOT NULL,
	CONSTRAINT Store_PK PRIMARY KEY (STORE_ID)
);
CREATE TABLE data_warehouse_metro.Product (
	PRODUCT_ID VARCHAR(6) NOT NULL, 
	PRODUCT_NAME VARCHAR(30) NOT NULL, 
	CONSTRAINT Product_PK PRIMARY KEY (PRODUCT_ID)
);
CREATE TABLE data_warehouse_metro.Supplier (
	SUPPLIER_ID VARCHAR(5) NOT NULL, 
	SUPPLIER_NAME VARCHAR(30) NOT NULL, 
	CONSTRAINT Supplier_PK PRIMARY KEY (SUPPLIER_ID)
);
CREATE TABLE data_warehouse_metro.Time (
	TIME_ID INT NOT NULL,
    DAY_OF_MONTH INT NOT NULL,
    DAY_OF_WEEK VARCHAR(9) NOT NULL,
    MONTH INT NOT NULL,
    QUARTER INT NOT NULL,
    YEAR INT NOT NULL,
    Week_no INT NOT NULL,
    Mid INT NOT NULL,
	CONSTRAINT Time_PK PRIMARY KEY (TIME_ID)
);

CREATE TABLE data_warehouse_metro.Sales (
	TRANSACTION_ID INT NOT NULL, 
	CUSTOMER_ID VARCHAR(4) NOT NULL, 
	STORE_ID VARCHAR(4) NOT NULL,
	PRODUCT_ID VARCHAR(6) NOT NULL, 
	SUPPLIER_ID VARCHAR(5) NOT NULL,
	TIME_ID INT NOT NULL,
	QUANTITY SMALLINT NOT NULL,
    TOTAL_SALE decimal(10,2) NOT NULL,
    CONSTRAINT FK_Sales_Customer FOREIGN KEY (CUSTOMER_ID) REFERENCES data_warehouse_metro.Customer(CUSTOMER_ID),
    CONSTRAINT FK_Sales_Store FOREIGN KEY (STORE_ID) REFERENCES data_warehouse_metro.Store(STORE_ID),
    CONSTRAINT FK_Sales_Product FOREIGN KEY (PRODUCT_ID) REFERENCES data_warehouse_metro.Product(PRODUCT_ID),
    CONSTRAINT FK_Sales_Supplier FOREIGN KEY (SUPPLIER_ID) REFERENCES data_warehouse_metro.Supplier(SUPPLIER_ID),
    CONSTRAINT FK_Sales_Time FOREIGN KEY (TIME_ID) REFERENCES data_warehouse_metro.Time(TIME_ID),
	CONSTRAINT Sales_PK PRIMARY KEY (TRANSACTION_ID, CUSTOMER_ID, STORE_ID, PRODUCT_ID, SUPPLIER_ID, TIME_ID)
);
